# Generated by Django 4.2.4 on 2023-09-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fnasc',
            new_name='fnac',
        ),
    ]
