# Generated by Django 4.2.4 on 2023-09-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0002_rename_fnasc_cliente_fnac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='usuario',
        ),
    ]
