# Generated by Django 4.2.4 on 2023-09-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0003_rename_user_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos/clientes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/fotos/productos'),
        ),
    ]
