# Generated by Django 4.2.4 on 2023-09-26 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppFinal', '0005_alter_cliente_avatar_alter_producto_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('cuit', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.CharField(max_length=150)),
                ('cliente', models.BooleanField(default=False)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AppFinal.provincia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VENDEDOR',
                'verbose_name_plural': 'VENDEDOR',
            },
        ),
    ]
